export const SELECTORS = {
  // Dropdowns with form.submit() onChange
  // Use name attributes — IDs are dynamically generated by WebObjects
  sessionTypeSelect: '[name="17.2.1.3.1.1.1.15"]',
  scenarioSelect: '[name="17.2.1.3.1.1.1.17"]',

  // Date field
  sessionDate: '[id="sessionDate"]',

  // GM fields
  gmNumber: '[id="gameMasterNumber"]',
  gmCharacterNumber: '[id="gameMasterCharacterNumber"]',
  gmName: '[id="gameMasterName"]',
  gmFactionSelect: '[id="gmFactionSelect"]',
  gmReputation: '[name*="35.15.5"]',

  // Reporting flags
  reportingA: '[name="17.2.1.3.1.1.1.27.1"]',
  reportingB: '[name="17.2.1.3.1.1.1.27.3"]',
  reportingC: '[name="17.2.1.3.1.1.1.27.5"]',
  reportingD: '[name="17.2.1.3.1.1.1.27.7"]',

  // Special faction objective checkboxes
  gmFactionObjectiveCheckboxes: 'input[name^="17.2.1.3.1.1.1.31.1."]',
  characterFactionObjectiveCheckboxes: 'input[name^="17.2.1.3.1.1.1.33.1."]',

  // Player row templates (N = 0-5)
  // IDs start with digits, so use attribute selectors
  playerNumber: (n: number): string => `[id="${n}playerNumber"]`,
  characterNumber: (n: number): string => `[id="${n}characterNumber"]`,
  characterName: (n: number): string => `[id="${n}characterName"]`,
  factionSelect: (n: number): string => `[id="${n}FactionSelect"]`,
  prestigePoints: (n: number): string => `[id="${n}prestigePoints"]`,
  consumesReplay: (n: number): string =>
    `[name*="${n}consumesReplay"], [name*="43.${n}.1.9"]`,

  // Add Extra Character button
  addExtraCharacter: '[name="17.2.1.3.1.1.1.41"]',

  // Form element
  form: 'form[name="editObject"]',
} as const;

export const STORAGE_KEY = 'pfs_session_report_pending';

export const TIMEOUT_MS = 30_000;

export const GAME_SYSTEM_TO_SELECT_VALUE: Record<string, string> = {
  PFS2E: '4',
};
